CarServiceProject/Models/ErrorViewModel.cs
namespace CarServiceProject.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

CarServiceProject/Controllers/AccountController.cs
using System.Diagnostics;
using CarServiceLibrary.Models;
using CarServiceLibrary.Models.Entities;
using CarServiceProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CarServiceProject.Controllers;

public class AccountController : Controller
{
    private readonly CarServiceDbContext _db;

    public AccountController(CarServiceDbContext context)
    {
        _db = context;
    }

    public IActionResult Test()
    {
        return View();
    }

    public IActionResult Login()
    {
        return View();
    }

    public IActionResult Registration()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> RegisterAccount(Users user)
    {
        if (ModelState.IsValid)
        {
            _db.Users.Add(user);
            await _db.SaveChangesAsync();
            return RedirectToAction("Login");
        }

        return Content("Не валидно!");
    }

    [HttpPost]
    public async Task<IActionResult> Login(string phone, string password)
    {
        if (!Validator.Validator.ValidatePhone(phone)) return Content("Не валидный телефон!");

        if (!Validator.Validator.ValidatePassword(password)) return Content("Не валидный пароль!");

        var findUser =
            await _db.Users.FirstOrDefaultAsync(x => x.TelephoneNumber == phone && x.PasswordUser == password);

        if (findUser != null)
        {
            return Content("Регистрация прошла успешно!");
        }

        return NotFound();
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

CarServiceProject/Controllers/AdminController.cs
using System.Diagnostics;
using CarServiceProject.Models;
using Microsoft.AspNetCore.Mvc;

namespace CarServiceProject.Controllers;

public class AdminController : Controller
{
    private readonly ILogger<AdminController> _logger;

    public AdminController(ILogger<AdminController> logger)
    {
        _logger = logger;
    }

    public IActionResult AdminPanel()
    {
        return View();
    }
    
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

CarServiceProject/Controllers/HomeController.cs
using System.Diagnostics;
using CarServiceLibrary.Models;
using CarServiceProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CarServiceProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private CarServiceDbContext _db;

        public HomeController(ILogger<HomeController> logger, CarServiceDbContext context)
        {
            _logger = logger;
            _db = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _db.Cars.ToListAsync());
        }
        

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CarServiceProject/Controllers/MainActionsController.cs
using System.Diagnostics;
using CarServiceLibrary.Models;
using CarServiceLibrary.ViewModels;
using CarServiceProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CarServiceProject.Controllers;

public class MainActionsController : Controller
{
    private readonly ILogger<MainActionsController> _logger;
	private CarServiceDbContext _db;

	public MainActionsController(ILogger<MainActionsController> logger, CarServiceDbContext context)
    {
        _logger = logger;
        _db = context;
    }

	

	#region MyRegion

	public IActionResult Diagnostic()
    {
        var services = _db.Services.Where(s => s.TypeId == 4).ToList();
        ServicesViewModel vm = new ServicesViewModel();
        vm.Services = services;
        return View(vm);
    }

	public async Task<IActionResult> Maintenance()
	{
		var services = _db.Services.Where(s => s.TypeId == 2).ToList();
		var vm = new ServicesViewModel();
        vm.Services = services;
		return View(vm);
	}

    public IActionResult GetService(int id)
    {
        var service = _db.Services.Find(id);
        return Json(service);
    }

	public IActionResult Repair()
    {
        return View();
    }

    public IActionResult Detailing()
    {
		var services = _db.Services.Where(s => s.TypeId == 3).ToList();
		ServicesViewModel vm = new ServicesViewModel();
		vm.Services = services;
		return View(vm);
	}

    public IActionResult Contacts()
    {
        return View();
    }

    public IActionResult OnMarks()
    {
        return View();
    }
    
    public IActionResult AboutService()
    {
        return View();
    }

    #endregion
    
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

CarServiceProject/Views/Admin/AdminPanel.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container">
    <!-- Button trigger modal -->
    <button type="button"
            class="btn btn-primary"
            data-bs-toggle="modal"
            data-bs-target="#AddService">
        Добавить услугу
    </button>

    <button type="button"
            class="btn btn-primary"
            data-bs-toggle="modal"
            data-bs-target="#EditService">
        Редактировать услугу
    </button>

    <!-- Modal AddService -->
    <div class="modal fade"
         id="AddService"
         tabindex="-1"
         aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"
                        id="exampleModalLabel">
                        Modal title
                    </h5>
                    <button type="button"
                            class="btn-close"
                            data-bs-dismiss="modal"
                            aria-label="Close">

                    </button>
                </div>
                <div class="modal-body">
                    Добавить услугу
                </div>
                <div class="modal-footer">
                    <button type="button"
                            class="btn btn-primary">
                        Сохранить
                    </button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal EditService -->
    <div class="modal fade"
         id="EditService"
         tabindex="-1"
         aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"
                        id="exampleModalLabel">
                        Modal title
                    </h5>
                    <button type="button"
                            class="btn-close"
                            data-bs-dismiss="modal"
                            aria-label="Close">

                    </button>
                </div>
                <div class="modal-body">
                    Редактировать услугу
                </div>
                <div class="modal-footer">
                    <button type="button"
                            class="btn btn-primary">
                        Сохранить
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

CarServiceProject/Views/Home/Index.cshtml
@model IEnumerable<CarServiceLibrary.Models.Entities.Cars> 

@{
    ViewData["Title"] = "Home Page";

}
<div class="main">
    <div class="container">
        <div class="row">
            <div class="col-12 d-flex flex-column align-items-start justify-content-center col-lg-6 col-xl-5 ">
                <div class="bg-light p-3 bg-opacity-50">
                    <h1>Выявим все неисправности!</h1>
                    <ul class="py-4">
                        <li class="fs-5">Осмотр авто по 40 пунктам</li>
                        <li class="fs-5">Компьютерная диагностика</li>
                        <li class="fs-5">Современное оборудование</li>
                        <li class="fs-5">Наш сервис имеет удобное местоположение</li>
                    </ul>
                    <a class="btn btn-danger fs-4" href="" role="button">Бесплатная диагностика</a>
                </div>
            </div>
            <div class="col-md-5 col-lg-5 offset-lg-1 d-none d-lg-block">
                <img class="main-img my-5" src="~/Images/obs.png" alt="">
            </div>
        </div>
    </div>
</div>


<div class="container text-center my-3">
    <h1 class="my-5">Наши услуги</h1>
    <div class="decor-line"></div>
    <div class="d-flex flex-column justify-content-center">
        <div class="row my-3">
            <div class="col">
                <div class="card p-4 border-radius-lg shadow-sm">
                    <img src="~/Images/Services/avtoelectronika.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <p class="card-text fs-4">Автоэлектроника</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card p-4 border-radius-lg shadow-sm">
                    <img src="~/Images/Services/tyuning.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                        <p class="card-text fs-4">Выхлопная система</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card p-4 border-radius-lg shadow-sm">
                    <img src="~/Images/Services/engine.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <p class="card-text fs-4">Двигатель</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="row my-3">
            <div class="col">
                <div class="card p-4 border-radius-lg shadow-sm">
                    <img src="~/Images/Services/cat13.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                        <p class="card-text fs-4">Диагностика автомобиля</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card p-4 border-radius-lg shadow-sm">
                    <img src="~/Images/Services/condition.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <p class="card-text fs-4">Заправка кондиционеров</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card p-4 border-radius-lg shadow-sm">
                    <img src="~/Images/Services/maslo.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <p class="card-text fs-4">Масло и фильтры</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="row my-3">
            <div class="col">
                <div class="card p-4 border-radius-lg shadow-sm">
                    <img src="~/Images/Services/obslujivanie.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <p class="card-text fs-4">Обслуживание</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card p-4 border-radius-lg shadow-sm">
                    <img src="~/Images/Services/podveska.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <p class="card-text fs-4">Подвеска</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card p-4 border-radius-lg shadow-sm">
                    <img src="~/Images/Services/akpp.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                        <p class="card-text fs-4">Ремонт АКПП</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <h1 class="my-5">Марки, которые мы обслуживаем</h1>
    <div class="decor-line"></div>
    <div class="d-flex flex-column justify-content-center">
        <div class="row row-cols-4">
            @foreach (var item in Model)
            {
                <div class="col my-3">
                    <div class="card p-4 border-radius-lg shadow-sm">
                        @*<img src="~/Images/Cars/@item.CarImage" class="card-img-top car-image" alt="...">*@
                        <img src="@("/Images/Cars/" + item.CarImage + ".png")" class="card-img-top car-image" alt="...">
                        <div class="card-body">
                            <p class="card-text fs-4">@item.CarName</p>
                        </div>
                    </div>
                </div>
            }
        </div>

        <div class="container my-5">
            <div class="row align-items-center">
                <div class="col">
                    <img src="~/Images/dvig.png" class="img" alt="...">
                </div>
                <div class="col">
                    <h2>Преимущества покупки запчастей в нашем автосервисе:</h2>
                    <div class="decor-line mb-3"></div>
                    <div class="text-start fs-5">
                        <p>Цена многих запчастей в нашем автосервисе ниже, чем в среднем по рынку, потому что поставщики заинтересованы в сотрудничестве с автосервисом из-за стабильного спроса и предлагают особые условия сотрудничества.</p>
                        <p>Также при покупке запчастей у нас Вы можете быть уверены, что все необходимое для ремонта Вашего автомобиля будет в наличии, либо доставлено в кратчайшие сроки, исключена возможность покупки лишних запчастей, необходимость их возврата, обмена. Мы экономим не только деньги, но и время Клиента.</p>
                        <p>В настоящее время около 4% запчастей, независимо от производителя может иметь брак, это норма для производства, иногда такие детали попадаются и визуально их сложно распознать. Мы сотрудничаем только с проверенными поставщиками и производителями, закупаем запчасти самого высокого качества, но для спокойствия Клиента мы также даем гарантию на все запчасти в случае их покупки у нас.</p>
                    </div>

                </div>
            </div>
        </div>
        <div>
            <div class="container">
                <div class="d-flex flex-column align-items-center ">
                    <h1>Почему выбирают нас</h1>
                    <div class="decor-line w-50"></div>
                    <div class="row row-cols-2 row-cols-lg-2 text-white my-3 text-start">
                        <div class="col my-2 bg-danger">
                            <h4 class="border-bottom border-light py-3">Квалифицированные специалисты</h4>
                            <p class="fs-5">Средний стаж наших мастеров 10 лет</p>
                        </div>
                        <div class="col my-2 bg-danger">
                            <h4 class="border-bottom border-light py-3">Все расходники в наличии</h4>
                            <p class="fs-5">Поможем в выборе расходных материалов для автомобилей и автосервисного оборудования в Казани</p>
                        </div>
                        <div class="col my-2 bg-danger">
                            <h4 class="border-bottom border-light py-3">Бесплатный осмотр ходовой</h4>
                            <p class="fs-5">Всем клиентам выполняем бесплатынй осмотр ходовой и даем рекомендации по дальнейшему обслуживанию</p>
                        </div>
                        <div class="col my-2 bg-danger">
                            <h4 class="border-bottom border-light py-3">Быстрое и качественное ТО автомобиля</h4>
                            <p class="fs-5">Мы придерживаемся регламента работ.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CarServiceProject/Views/MainActions/AboutService.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="container my-5 d-flex flex-column align-items-center">
   <h1 class="my-3">Об автосервисе</h1>
   <div class="my-3">
       <p class="fs-5">
           Уже более 7 лет мы добросовестно выполняем свою работу. 
           Наш автосервис предлагает полный спектр ремонтных работ, 
           от электронной диагностики автомобиля до замены любой его запчасти в городе Казани.
       </p>

       <p class="fs-5">
           Вы всегда получаете гарантированно качественную работу от наших профессионалов, 
           и всегда можете быть уверенными в надежной работе своего автомобиля.
       </p>

       <p class="fs-5">
           Так же получаете нашу гарантию на все виды работ.
       </p>

       <p class="fs-5">
           В комплексных работах участвуют несколько специалистов, 
           каждый из которых отвечает за свою часть работы.
       </p>

       <p class="fs-5">
           Специалисты узкого профиля повышают работоспособность сервиса и качество выполнения работ. 
           Обслуживание автомобиля организовано согласно требованиям заводов-изготовителей. 
           Оборудование техцентра соответствует всем современным требованиям.
       </p>
   </div>
   
</div>

CarServiceProject/Views/MainActions/Contacts.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="container my-5">
    <div class="row">
        <div class="col text-center">
            <h2 class="m-3">
                Контакты автосервиса
            </h2>
            <div class="decor-line">

            </div>
            <div class="contacts">
                <div class="contacts-item">
                    <img class="contacts-img"
                         src="~/Images/home.png"
                         alt=""/>
                    <div class="contacts-body">
                        <h5>Адрес</h5>
                        <p>г. Казань, ул. Большая крассная 55</p>
                    </div>
                </div>
                <div class="contacts-item">
                    <img class="contacts-img"
                         src="~/Images/phone-call.png"
                         alt=""/>
                    <div class="contacts-body">
                        <h5>Телефон</h5>
                        <p>8 (903) 305-16-86</p>
                    </div>
                </div>
                <div class="contacts-calendar my-3">
                    <div class="contacts-inner">
                        <dl class="week-day">
                            <dt>Понедельник</dt>
                            <dd class="week-day__line"></dd>
                            <dd>09:00-20:00</dd>
                        </dl>
                        <dl class="week-day ">
                            <dt>Вторник</dt>
                            <dd class="week-day__line"></dd>
                            <dd>09:00-20:00</dd>
                        </dl>
                        <dl class="week-day ">
                            <dt>Среда</dt>
                            <dd class="week-day__line"></dd>
                            <dd>09:00-20:00</dd>
                        </dl>
                        <dl class="week-day ">
                            <dt>Четверг</dt>
                            <dd class="week-day__line"></dd>
                            <dd>09:00-20:00</dd>
                        </dl>
                        <dl class="week-day ">
                            <dt>Пятница</dt>
                            <dd class="week-day__line"></dd>
                            <dd>09:00-20:00</dd>
                        </dl>
                        <dl class="week-day ">
                            <dt>Суббота</dt>
                            <dd class="week-day__line"></dd>
                            <dd>09:00-20:00</dd>
                        </dl>
                        <dl class="week-day ">
                            <dt>Воскресенье</dt>
                            <dd class="week-day__line"></dd>
                            <dd>09:00-20:00</dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
        <div class="col text-center">
            <h2 class="m-3">Проезд к автосервису</h2>
            <div id="map" class="map border ">
                <script src="https://api-maps.yandex.ru/2.1/?apikey=ваш API-ключ&lang=ru_RU"
                        type="text/javascript"></script>
            </div>
        </div>
    </div>
</div>

CarServiceProject/Views/MainActions/Detailing.cshtml
@model CarServiceLibrary.ViewModels.ServicesViewModel
@{
    
}
<div class="detailing-header">
	<div class="container h-100">
		<div class="d-flex w-100 h-100 flex-column align-items-center justify-content-center text-light">
			<h1 class="fw-bold" style="font-size: 64px;">Detailing Studio</h1>
			<p class="bg-dark fs-3 bg-opacity-50">все виды детейлинга и восстановления вида автомобиля</p>	
			<a class="btn fw-bold btn-outline-danger fs-4" href="" role="button">УЗНАТЬ БОЛЬШЕ</a>
		</div>
	</div>
</div>

<div class="detailing-bg">
	<div class="container">
		<div class="row row-cols-4 row-cols-lg-4">
			@foreach(var item in Model.Services)
			{
				<div class="col my-4">
					<div id="serviceModal" class="card bg-dark bg-opacity-50 p-3" onclick="showModal(@item.Id)" data-bs-toggle="modal" data-bs-target="#GetService">
						<img src="~/Images/Detailing/@item.ServicesImage" class="card-img-top" alt="...">
						<div class="card-body d-flex flex-column text-center align-items-center">
							<h5 class="card-title text-light">@item.ServiceName</h5>
							<a href="#" class="btn btn-outline-danger">Узнать стоимость</a>
						</div>
					</div>
				</div>
			}
		</div>
	</div>
        <!-- Modal OrderService -->
<div class="modal fade"
     id="GetService"
     tabindex="-1"
     aria-labelledby="orderService"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form>
                <div class="modal-header text-center justify-content-center">
                    <h2 class="modal-title"
                        id="ServiceName">
                    </h2>
                </div>
                <div class="modal-body text-start">
                    <div class="row m-3">
                        <div class="form-group">
                            <label class="fw-bold m-1" for="name">Ваше имя</label>
                            <input type="text" class="form-control py-2 fs-5" id="name" placeholder="Имя">
                        </div>
                    </div>
                    <div class="row m-3">
                        <div class="col">
                            <div class="form-group">
                                <label class="fw-bold m-1" for="car">Марка</label>
                                <input type="text" class="form-control py-2 fs-5" id="car" placeholder="Марка машины">
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label class="fw-bold m-1" for="carModel">Модель</label>
                                <input type="text" class="form-control py-2 fs-5" id="carModel" placeholder="Модель машины">
                            </div>
                        </div>
                    </div>
                    <div class="row m-3">
                        <div class="form-group">
                            <label class="fw-bold m-1" for="comment">Комментарий</label>
                            <input type="text" class="form-control py-2 fs-5" id="comment" placeholder="Комментарий">
                        </div>
                    </div>
                    <div class="row m-3">
                        <div class="form-group">
                            <label class="fw-bold m-1" for="phone">Телефон</label>
                            <input type="text" class="form-control py-2 fs-5" id="phone" placeholder="Номер телефона">
                        </div>
                    </div>
                </div>
            </form>

            <div class="modal-footer">
                <div class="row mx-5 text-center">
                    <button type="submit" class="btn btn-danger fw-bold fs-4">Оставить заявку</button>
                    <p class="fs-6 p-2">Оперативно перезваниваем в рабочее время</p>
                </div>
            </div>

        </div>

    </div>
</div>
</div>

@section Scripts {
        <script type="text/javascript">
            var showModal = function(id)
            {
              $.ajax({
               type: "POST",
               url: "/MainActions/GetService",
               data: { id:id},
               success: function(service){
                 $("#GetService").modal('show');
                  $("#ServiceName").text(service.serviceName);
               }
              })
            }
            </script>
}

CarServiceProject/Views/MainActions/OnMarks.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="container my-5">
    По маркам
</div>

CarServiceProject/Views/MainActions/Repair.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container">Ремонт</div>

CarServiceProject/Views/Shared/_Layout.cshtml
@{
	var Auth = false;
}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - WebApplication1</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>

<body style="height: 100%;">
	<header id="header">
		<nav class="container navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white">
			<div class="container-fluid d-flex justify-content-between">
				<div class="d-flex flex-column align-items-center">
					<img class="img" src="~/Images/logo.png" style="width: 120px;" alt="">
					<a class="navbar-brand fs-5 fw-bold" asp-area="" asp-controller="Home" asp-action="Index">SERVICE</a>
				</div>
				
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<form class="d-flex w-50" role="search">
					<input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Search">

				</form>
				<div class="d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							@if (Auth)
							{
								<a class="nav-link text-dark fs-5" asp-area="" asp-controller="Account" asp-action="Test">Личный кабинет</a>
							}
							else
							{
								<a class="nav-link text-dark fs-5" asp-area="" asp-controller="Account" asp-action="Login">Войти</a>
							}
						</li>
					</ul>
	

				</div>
			</div>
		</nav>
		<div class="header-categories bg-dark">
			<div class="container d-flex">
					<ul class="navbar-nav  w-100 justify-content-between fw-bold d-sm-inline-flex py-3 flex-row">
						<li class="nav-item px-3">
							<a class="nav-link link text-light fs-5" asp-area="" asp-controller="MainActions" asp-action="Diagnostic">Диагностика</a>
						</li>
						<li class="nav-item px-3">
							<a class="nav-link link text-light fs-5" asp-area="" asp-controller="MainActions" asp-action="Maintenance">Обслуживание</a>
						</li>
						@*<li class="nav-item px-3">
							<a class="nav-link link text-light fs-5" asp-area="" asp-controller="MainActions" asp-action="Repair">Ремонт</a>
						</li>*@
						<li class="nav-item px-3">
							<a class="nav-link link text-light fs-5" asp-area="" asp-controller="MainActions" asp-action="Detailing">Детейлинг</a>
						</li>
						@*<li class="nav-item px-3">
							<a class="nav-link link text-light fs-5" asp-area="" asp-controller="MainActions" asp-action="OnMarks">По маркам</a>
						</li>*@
						<li class="nav-item px-3">
							<a class="nav-link link text-light fs-5" asp-area="" asp-controller="MainActions" asp-action="AboutService">Об автосервисе</a>
						</li>
						<li class="nav-item px-3">
							<a class="nav-link link text-light fs-5" asp-area="" asp-controller="MainActions" asp-action="Contacts">Контакты</a>
						</li>
					</ul>
				</div>
		</div>
		
	</header>

		<main role="main" class="pb-3">
			@RenderBody()
		</main>

	<footer id="footer" class="border-top bg-dark text-light">
		<div class="container d-flex justify-content-between py-5 px-3">
			<div class=" text-center px-5">
				<p class="fs-5">Компания</p>
				<ul class="nav flex-column">
					<li class="nav-item">
						<a class="nav-link link text-light fs-6" href="#">О компании</a>
					</li>
					<li class="nav-item">
						<a class="nav-link link text-light fs-6" href="#">Адреса</a>
					</li>
					<li class="nav-item">
						<a class="nav-link link text-light fs-6" href="#">Гарантии</a>
					</li>
					<li class="nav-item">
						<a class="nav-link link text-light fs-6" href="#">Список услуг</a>
					</li>
				</ul>
			</div>

			<div class="d-flex flex-column align-items-center">
				<div class="fs-1">SERVICE</div>
				<img class="img" src="~/Images/logo.png" style="width: 300px;" alt="">
			</div>

			<div class=" text-center px-5">
				<p class="fs-5">Контакты</p>
				<ul class="nav flex-column">
					<li class="nav-item">
						<a class="nav-link link text-light fs-6" href="#">Telegram</a>
					</li>
					<li class="nav-item">
						<a class="nav-link link text-light fs-6" href="#">Instagram</a>
					</li>
					<li class="nav-item">
						<a class="nav-link link text-light fs-6" href="#">Телефон</a>
					</li>
					<li class="nav-item">
						<a class="nav-link link text-light fs-6" href="#">Email</a>
					</li>
				</ul>
			</div>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>